kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  namespace: gedigital
spec:
  selector:
    app: nginx
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  type: LoadBalancer